title: 子狐飼育日記
description: > # this means to ignore newlines until "baseurl:"
  A quick brown fox jumps over the lazy dog.
# permalink: ':title/'

banner:
  video: mountains.mp4 # add banner video. Add your video file to the folder video
  title: # add banner title
  description: # add banner description

social:
  twitter: iFox1002

paginate: 6
paginate_path: /page-:num/

url: "https://jinyu.li" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/i-fox.github.io" # the subpath of your site, e.g. /blog

assets:
  styles:  /assets/styles
  fonts:   /assets/fonts
  images:  /assets/images
  videos:  /assets/videos
  scripts: /assets/scripts

markdown: kramdown

gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [ _pages ]
exclude: [ CNAME, LICENSE, gulpfile.js, package.json, yarn.lock ]
